[package]
name = "sonos-web"
version = "0.1.0"
authors = ["Denys Vitali <denys@denv.it>"]
edition = "2018"

[dependencies]
actix-web = {repository="actix/actix-web"}
actix-rt = "1.0.0-alpha.1"
sonos = "0.1.3"
regex = "1.3.1"
serde = { version = "1.0", features = ["derive"] }